pipeline{
   agent any
	stages{
      stage("test") {
         steps{
            echo "hello world!"
         }
      stage("build") {
         steps{
            echo "Build"
         }
      stage("deploy") {
         steps{
            echo "deploy"
         }
      }
   }
}
   }
}